export const ORE_GLYPHS: Record<string, string[]> = {
  emberite: [
    "..oooo..",
    ".oBBBbo.",
    "oBccBBbo",
    "oBcBBBbo",
    "obBBBBbo",
    ".obbBbo.",
    "..oooo..",
    "........",
  ],
  coldiron: [
    "...o....",
    "..oBBo..",
    ".oBcBBo.",
    "oBBcBBbo",
    "obBBBBbo",
    ".obbBbo.",
    "..oooo..",
    "........",
  ],
  stormore: [
    "....o...",
    "..oBBo..",
    ".oBcBBo.",
    "oBBBBBbo",
    "oBbBBbbo",
    ".oBBboo.",
    "..oooo..",
    "........",
  ],
  voidslag: [
    "..oooo..",
    ".obbbbo.",
    "ob....bo",
    "ob.cc.bo",
    "ob....bo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  thornite: [
    "...o.o..",
    ".o.b.o..",
    "o.bBb.o.",
    ".obBBbo.",
    "oobBBboo",
    ".obbbbo.",
    "..o.o...",
    "........",
  ],
  blastore: [
    ".oooooo.",
    "obBccBbo",
    "oBBbbBBo",
    "obb..bbo",
    "oBB..BBo",
    "obBBBBbo",
    ".oooooo.",
    "........",
  ],
  goldvein: [
    "..oooo..",
    ".obcBbo.",
    "obBcBBbo",
    "oBBBcBbo",
    "obBBcBbo",
    ".obbBbo.",
    "..oooo..",
    "........",
  ],
  nightiron: [
    ".oooooo.",
    "obbbbbbo",
    "obBccBbo",
    "obBBBbbo",
    "obbbbbbo",
    "obbbbbbo",
    ".oooooo.",
    "........",
  ],
  mossore: [
    "..o..o..",
    ".obooBo.",
    "obBBbBbo",
    "oBbccbBo",
    "obBBBBbo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  bloodstone: [
    "..oooo..",
    ".oBBBBo.",
    "oBccBBbo",
    "oBBBBBbo",
    ".obbBbo.",
    "..obbo..",
    "...oo...",
    "....o...",
  ],
  moonslag: [
    "...ooo..",
    "..oBBBo.",
    ".oBc..bo",
    "oBB...bo",
    "oBB..bbo",
    ".oBBBBo.",
    "..oooo..",
    "........",
  ],
  ashvein: [
    "..o.oo..",
    ".obBbBo.",
    "oBb.cBbo",
    "obBBBBbo",
    "oBbBbBbo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  rimeore: [
    "...c....",
    "..oBBo..",
    ".oBcBBo.",
    "oBBBBBbo",
    "obBcBBbo",
    ".oBBBBo.",
    "..oooo..",
    "........",
  ],
  brambleiron: [
    ".o..o.o.",
    "o.obBo.o",
    ".obBBbo.",
    "oobccboo",
    ".obBBbo.",
    "o.obbo.o",
    ".o..o.o.",
    "........",
  ],
  starslag: [
    "...c....",
    "..oBo...",
    ".oBBBo..",
    "cBBBBBBc",
    ".oBBBo..",
    "..oBo...",
    "...c....",
    "........",
  ],
};

export const CRYSTAL_GLYPHS: Record<string, string[]> = {
  "cinder-crystal": [
    "...oo...",
    "..oCCo..",
    ".oCcCCo.",
    "oCcccCCo",
    "oCcccCCo",
    ".oCCCCo.",
    "..oooo..",
    "........",
  ],
  "frost-crystal": [
    "...c....",
    "..oCo...",
    ".oCcCo..",
    "oCcccCo.",
    ".oCcCo..",
    "..oCo...",
    "...o....",
    "........",
  ],
  "bolt-crystal": [
    "....c...",
    "...oCo..",
    "..oCCCo.",
    ".oCcccC.",
    "oCCCCCo.",
    ".oooo...",
    "..o.....",
    "........",
  ],
  "void-crystal": [
    "..oooo..",
    ".oCCCCo.",
    "oC....Co",
    "oC....Co",
    "oC....Co",
    ".oCCCCo.",
    "..oooo..",
    "........",
  ],
  "vine-crystal": [
    "...o.o..",
    "..oCoCo.",
    ".oCcCCo.",
    "oCcccCCo",
    ".oCCCCo.",
    "..o.o...",
    "...o....",
    "........",
  ],
  "boom-crystal": [
    "..oooo..",
    ".oCCCCo.",
    "oCcCCcCo",
    "oCCCCCCo",
    "oCcCCcCo",
    ".oCCCCo.",
    "..oooo..",
    "........",
  ],
  "dawn-crystal": [
    "...oo...",
    "..oCCo..",
    ".oCCCCo.",
    "oCCccCCo",
    ".oCCCCo.",
    "..oooo..",
    "...oo...",
    "........",
  ],
  "dusk-crystal": [
    ".oooooo.",
    "oCCCCCCo",
    "oCCccCCo",
    "oCccccCo",
    ".oCCCCo.",
    "..oooo..",
    "...oo...",
    "........",
  ],
  "heart-crystal": [
    ".oo..oo.",
    "oCCooCCo",
    "oCCccCCo",
    ".oCccCo.",
    "..oCCo..",
    "...oo...",
    "........",
    "........",
  ],
  "grave-crystal": [
    ".oooooo.",
    "oCCCCCCo",
    "oC....Co",
    "oC.cc.Co",
    "oC....Co",
    "oCCCCCCo",
    ".oooooo.",
    "........",
  ],
  "tide-crystal": [
    "...oo...",
    ".ooCCoo.",
    "oCCccCCo",
    "oCccccCo",
    ".oCCCCo.",
    "..oCCo..",
    "...oo...",
    "........",
  ],
  "spark-crystal": [
    "c..o..c.",
    ".oCCCo..",
    "oCcccCo.",
    "oCcccCo.",
    ".oCCCo..",
    "..o.o...",
    ".c...c..",
    "........",
  ],
  "bloom-crystal": [
    "..o.c.o.",
    ".oCoCoCo",
    "oCCccCCo",
    ".oCCCCo.",
    "..oCCo..",
    "...oo...",
    "........",
    "........",
  ],
  "shade-crystal": [
    "..oooo..",
    ".obbbbo.",
    "obCccCbo",
    "oCccccCo",
    "obCCCCbo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  "lantern-crystal": [
    "...oo...",
    "..oCCo..",
    ".oCccCo.",
    "oCCccCCo",
    ".oooooo.",
    "...hh...",
    "...hh...",
    "........",
  ],
};

export const WEAPON_GLYPHS: Record<string, string[]> = {
  "ember-mallet": [
    "........................",
    ".................ff.....",
    "..............oooooo....",
    ".............oBBBBBBo...",
    "............oBBccBBBBo..",
    "...........oBBCCCCBBBo..",
    ".owwHHHHwwo.oBBccBBBBo..",
    ".owhhhhhww...oBBBBBBo...",
    "..orooooro....oooooo....",
    "................ff......",
    "........................",
    "........................",
  ],
  "ice-peen": [
    "........................",
    "....................iC..",
    "..................iiCCi.",
    ".................oBBCCi.",
    ".owHHHHHHHHwooo.oBBBBCo.",
    ".owhhhhhhhhwrrr.oBBBBo..",
    "..oooooooooo......ooo...",
    "....i..i................",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  "storm-hammer": [
    "........................",
    ".............o.o.o.o....",
    "...........ooooooooo....",
    "..........oBBCcCCBBo....",
    "..........oBCCCCCCBo....",
    ".owwHHHwwo.oBBCcCBBo....",
    ".owhhhhhwo.oBBBBBBBo....",
    "..oroooro...ooBBBoo.....",
    "..............o.o.......",
    "........................",
    "........................",
    "........................",
  ],
  "void-maul": [
    "........................",
    "...........oooooooooo...",
    "..........oBBBBBBBBBBo..",
    ".........oBB......BBBo..",
    ".owHHHwo.oBB.oCCo.BBBo..",
    ".owhhhwo.oBB.oCCo.BBBo..",
    "..ooooo..oBB......BBBo..",
    ".........oBBBBBBBBBBBo..",
    "..........oooooooooo....",
    "........................",
    "........................",
    "........................",
  ],
  "thorn-hammer": [
    "........................",
    "....s.........s...s.....",
    "...s.s......ooBBo..s....",
    "..s...s....oBBCCBBo.s...",
    ".owHHHHHwooBBCCCCBo.....",
    ".owsshhswwoBBBBBBoo.....",
    "..s.ooo.s...oooo.s......",
    "...s...s.........s......",
    "....s...................",
    "........................",
    "........................",
    "........................",
  ],
  "blast-sledge": [
    "........................",
    "..........ooooooooooo...",
    ".........oBBBcccBBBBo...",
    "........oBBrBBBBBrBBo...",
    ".owHHwo.oBBBB..BBBBo....",
    ".owhhwo.oBBBB..BBBBo....",
    "..oooo..oBBrBBBBBrBBo...",
    ".........oBBBcccBBBo....",
    "..........ooooooooo.....",
    "........................",
    "........................",
    "........................",
  ],
  "gold-hammer": [
    "........................",
    "............o..C..o.....",
    "...........oBooooBo.....",
    "..........oBBCCCCBBo....",
    "..........oBcCCCCBBo....",
    ".owwHHHwo.oBBCCCCBBo....",
    ".owhhhhwo..oBBBBBBo.....",
    "..orCCro....oooooo......",
    "....oo..................",
    "........................",
    "........................",
    "........................",
  ],
  "night-maul": [
    "........................",
    "..........oo......oo....",
    ".........oBBo....oBBo...",
    "........oBBBBooooBBBo...",
    ".owHHHwo.oBBCCCCBBBBo...",
    ".owhhhwo.oBBBBBBBBBBo...",
    "..ooooo...oBBBBBBBBo....",
    "...........ooBBBBoo.....",
    ".............oooo.......",
    "........................",
    "........................",
    "........................",
  ],
  "root-mallet": [
    "........................",
    "..............o..s......",
    ".............oBbBBo.s...",
    "............oBBccBBo....",
    ".oHhHhHhwo..oBbccbBo....",
    ".ohhHhHhwo..oBBBBBBo....",
    "..o.ooo.o....oBbBBo.....",
    "....o.o.......o..o......",
    ".....o..................",
    "........................",
    "........................",
    "........................",
  ],
  "bone-hammer": [
    "........................",
    "...................oCo..",
    "..................oBBBo.",
    ".................oBcBBo.",
    ".oHhHoHhHoHhoooo.oBBBBo.",
    ".ohhHohhHohhoooo.oBBBo..",
    "..................oBBo..",
    "...................oCo..",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  "moon-peen": [
    "........................",
    ".....................oC.",
    "...................ooCCo",
    "..................oBBCCo",
    ".owHHHHHHHHHHHwo..oBBBo.",
    ".owhhhhhhhhhhhwo...oBo..",
    "..ooooooooooooo.C...o...",
    "...............CC.......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  "ash-sledge": [
    "........................",
    ".........oooooooooooo...",
    "........oBBo.n.oBBBBo...",
    ".......oBBBBBBBBBBBBo...",
    ".owHHHo.oBBrBBBBBrBBo...",
    ".owhhho.oBBBBBBBBBBo....",
    "..ooooo.oBBo.n.oBBBo....",
    ".........oooooooooo.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  "rime-hammer": [
    "........................",
    ".............i.C.i......",
    "............oBCCCBo.....",
    "...........oBBCCCBBo....",
    ".owwHHHwo..oBBBBBBo.....",
    ".owhhhhwo...oBBBBo......",
    "..oooooo.....i.i.i......",
    "..............i.i.......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  "bramble-maul": [
    "........................",
    "....s...oooooo...s......",
    "...s.s.oBCCCCBo.s.s.....",
    "..s...oBBBBBBBBo..s.....",
    ".owHHHooBBBBBBoo........",
    ".owsswooBBBBBBoo........",
    "..s.oo.s.oooo.s.s.......",
    "...s..s........s........",
    "....s...................",
    "........................",
    "........................",
    "........................",
  ],
  "star-hammer": [
    "........................",
    "...................C.oC.",
    "..............C..o.oBBCo",
    "...............oBo.oBBBo",
    ".owHHHHHHHHHHHooBBBoBBo.",
    ".owhhhhhhhhhhhooBBBoBo..",
    "...............oBo.oBo..",
    "..............C....C....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
};

function shade(hex: string, amt: number) {
  const n = parseInt(hex.replace("#", ""), 16);
  const r = Math.max(0, Math.min(255, ((n >> 16) & 255) + amt));
  const g = Math.max(0, Math.min(255, ((n >> 8) & 255) + amt));
  const b = Math.max(0, Math.min(255, (n & 255) + amt));
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, "0")}`;
}

export function weaponGlyph(hammerId: string): string[] {
  return WEAPON_GLYPHS[hammerId] ?? WEAPON_GLYPHS["ember-mallet"]!;
}

export function pieceGlyph(id: string): string[] {
  return ORE_GLYPHS[id] ?? CRYSTAL_GLYPHS[id] ?? weaponGlyph(id);
}

export function piecePalette(id: string, color: string, crystal = "#fff4c8"): Record<string, string> {
  return {
    o: "#1a1210",
    h: "#2a1c14",
    H: "#7a5230",
    b: shade(color, -24),
    B: color,
    c: shade(crystal, -10),
    C: crystal,
    w: "#5a3820",
    r: "#3a3c3a",
    s: "#3d7a45",
    f: "#ff9a3c",
    i: "#c5eaf6",
    n: "#2a2c28",
  };
}

export function drawWeaponGlyph(
  ctx: CanvasRenderingContext2D,
  hammerId: string,
  x: number,
  y: number,
  ang: number,
  px: number,
  ore: string,
  crystal: string,
  flash = false,
) {
  const rows = weaponGlyph(hammerId);
  const h = rows.length;
  const w = rows[0]?.length ?? 1;
  const pal = piecePalette(hammerId, flash ? "#fff4c8" : ore, flash ? "#ffffff" : crystal);
  ctx.save();
  ctx.imageSmoothingEnabled = false;
  ctx.translate(x, y);
  ctx.rotate(ang);
  const ox = 1;
  const oy = -Math.floor(h / 2);
  for (let j = 0; j < h; j++) {
    const row = rows[j]!;
    for (let i = 0; i < w; i++) {
      const ch = row[i]!;
      if (ch === ".") continue;
      ctx.fillStyle = pal[ch] ?? ore;
      ctx.fillRect((ox + i) * px, (oy + j) * px, px, px);
    }
  }
  ctx.restore();
}
